services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    hostname: openldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=SpringFramework Org
      - LDAP_DOMAIN=springframework.org
      - LDAP_ADMIN_PASSWORD_FILE=/run/secrets/ldap_admin_password
    command: --copy-service --loglevel debug
    volumes:
      - ./ldap-data/database:/var/lib/ldap
      - ./ldap-data/config:/etc/ldap/slapd.d
    secrets:
      - ldap_admin_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "ldapsearch -x -H ldap://localhost -b dc=springframework,dc=org -D cn=admin,dc=springframework,dc=org -w \"$(cat /run/secrets/ldap_admin_password)\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  phpldapadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpldapadmin
    image: custom-phpldapadmin:0.9.0
    container_name: phpldapadmin-ui
    hostname: phpldapadmin-ui
    ports:
      - "6080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap-server
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

secrets:
  ldap_admin_password:
    file: ./ldap_admin_password.txt