version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    hostname: my-openldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=SpringFramework Org
      - LDAP_DOMAIN=springframework.org
      - LDAP_ADMIN_PASSWORD=password
    command: --copy-service --loglevel debug
    volumes:
      - ./ldap-data/database:/var/lib/ldap
      - ./ldap-data/config:/etc/ldap/slapd.d
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin-ui
    hostname: phpldapadmin-ui
    ports:
      - "6080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap-server
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    restart: unless-stopped