---
services:
  user-ldap:
    image: "${TESTING_IMAGE}"
    environment:
      - LDAP_HOST=openldap-server
    depends_on:
      openldap:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  integration-tester:
    image: bretfisher/netshoot:stable-20230820-cefc587
    command: ["curl", "-f", "http://user-ldap:8080/users"]
    depends_on:
      user-ldap:
        condition: service_healthy

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    hostname: openldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=SpringFramework Org
      - LDAP_DOMAIN=springframework.org
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    command: >
      sh -c "
      --copy-service --loglevel debug &&
      /bin/bash /scripts/populate_sample_data.sh
      "
    volumes:
      - ./users.ldif:/tmp/users.ldif
      - ./populate_sample_data.sh:/scripts/populate_sample_data.sh
    restart: unless-stopped
    healthcheck:
      test: |-
        ldapsearch -x -H ldap://localhost \
          -b dc=springframework,dc=org \
          -s base \
          -D cn=admin,dc=springframework,dc=org \
          -w "${LDAP_ADMIN_PASSWORD}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  populate-sample-data:
    image: alpine:latest
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 && 
             docker cp /app/users.ldif openldap-server:/users.ldif &&
             docker exec -it openldap-server ldapadd -x -D 'cn=admin,dc=springframework,dc=org' -w '${LDAP_ADMIN_PASSWORD}' -f /users.ldif"
    depends_on:
      openldap:
        condition: service_started
