---
services:
  user-ldap:
    image: "${TESTING_IMAGE}"
    environment:
      - LDAP_HOST=openldap-server
    depends_on:
      - openldap
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  integration-tester:
    image: curlimages/curl:8.9.0
    command:
      [
        "--retry",
        "5",
        "--retry-delay",
        "5",
        "--retry-connrefused",
        "-f",
        "http://user-ldap:8080/users",
      ]
    depends_on:
      user-ldap:
        condition: service_healthy

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    hostname: openldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=SpringFramework Org
      - LDAP_DOMAIN=springframework.org
      - LDAP_ADMIN_PASSWORD_FILE=/run/secrets/ldap_admin_password
    command: --copy-service --loglevel debug
    volumes:
      - ./ldap-data/database:/var/lib/ldap
      - ./ldap-data/config:/etc/ldap/slapd.d
    secrets:
      - ldap_admin_password
    restart: unless-stopped
    healthcheck:
      test: |-
        ldapsearch -x -H ldap://localhost \
          -b dc=springframework,dc=org \
          -s base \
          -D cn=admin,dc=springframework,dc=org \
          -w "$(cat /run/secrets/ldap_admin_password)"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

secrets:
  ldap_admin_password:
    file: ./ldap_admin_password.txt
