FROM osixia/phpldapadmin:0.9.0

RUN sed -i '/nginx/d' /etc/apt/sources.list \
    && rm -f /etc/apt/sources.list.d/nginx.list \
    && apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=5 \
  CMD curl -f http://localhost || exit 1