---
spring:
  application:
    name: user-management-ldap

  ldap:
    urls: ldap://${LDAP_HOST:localhost}:${LDAP_PORT:1389}
    base: dc=springframework,dc=org
    username: cn=admin,dc=springframework,dc=org
    password: password
