spring:
  application:
    name: user-management-ldap

  ldap:
    urls: ldap://localhost:389
    base: dc=springframework,dc=org
    username: cn=admin,dc=springframework,dc=org
    password: password