---
services:
  openldap:
    image: bitnami/openldap:2.6.10
    container_name: openldap-server
    hostname: openldap-server
    ports:
      - "8389:1389"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ROOT=dc=springframework,dc=org
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - BITNAMI_DEBUG=true
    volumes:
      - ./ldap-data/import:/ldifs
    restart: unless-stopped
    healthcheck:
      test: |-
        ldapsearch -x -H ldap://localhost:1389 \
          -b dc=springframework,dc=org \
          -s base \
          -D cn=admin,dc=springframework,dc=org \
          -w "${LDAP_ADMIN_PASSWORD}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
