---
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-server
    hostname: openldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=SpringFramework Org
      - LDAP_DOMAIN=springframework.org
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    command: --copy-service --loglevel debug
    volumes:
      - ./ldap-data/import:/container/service/slapd/assets/config/bootstrap/ldif/custom
    restart: unless-stopped
    healthcheck:
      test: |-
        ldapsearch -x -H ldap://localhost \
          -b dc=springframework,dc=org \
          -s base \
          -D cn=admin,dc=springframework,dc=org \
          -w "${LDAP_ADMIN_PASSWORD}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
