---
services:
  user-ldap:
    image: "${TESTING_IMAGE}"
    environment:
      - LDAP_HOST=openldap-server
      - LDAP_PORT=389
      - LDAP_PASSWORD=${LDAP_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  integration-tester:
    image: bretfisher/netshoot:stable-20230820-cefc587
    command: ["curl", "-f", "http://user-ldap:8080/users"]
    depends_on:
      user-ldap:
        condition: service_healthy
