---
services:
  openldap:
    environment:
      - LDAP_ADMIN_PASSWORD_FILE=/run/secrets/ldap_admin_password
    secrets:
      - ldap_admin_password
    healthcheck:
      test: |-
        ldapsearch -x -H ldap://localhost:1389 \
          -b dc=springframework,dc=org \
          -s base \
          -D cn=admin,dc=springframework,dc=org \
          -w "$(cat /run/secrets/ldap_admin_password)"

secrets:
  ldap_admin_password:
    file: ./ldap_admin_password.txt
