---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manage-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manage-ldap
  template:
    metadata:
      labels:
        app: user-manage-ldap
    spec:
      containers:
        - name: user-manage-ldap
          image: ${TESTING_IMAGE}
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: LDAP_HOST
              value: ldap
      imagePullSecrets:
        - name: regcred
