---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-bootstrap-ldif
data:
  users.ldif: |
    dn: ou=groups,dc=springframework,dc=org
    objectclass: top
    objectclass: organizationalUnit
    ou: groups
    
    dn: uid=dbrown,ou=groups,dc=springframework,dc=org
    cn: David Brown
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Brown
    uid: dbrown
    userpassword: password5
    
    dn: uid=john,ou=groups,dc=springframework,dc=org
    cn: John
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: John
    uid: john
    userpassword: 12345
    
    dn: uid=msmith,ou=groups,dc=springframework,dc=org
    cn: Mary Smith
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Smith
    uid: msmith
    userpassword: password2
    
    dn: uid=pjones,ou=groups,dc=springframework,dc=org
    cn: Peter Jones
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Jones
    uid: pjones
    userpassword: password3
    
    dn: uid=swilliams,ou=groups,dc=springframework,dc=org
    cn: Susan Williams
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Williams
    uid: swilliams
    userpassword: password4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manage-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manage-ldap
  template:
    metadata:
      labels:
        app: user-manage-ldap
    spec:
      containers:
        - name: user-manage-ldap
          image: ${TESTING_IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: LDAP_HOST
              value: openldap-service
          volumeMounts:
            - name: bootstrap-volume
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: bootstrap-volume
          configMap:
            name: openldap-bootstrap-ldif
---
apiVersion: v1
kind: Service
metadata:
  name: user-manage-ldap
spec:
  selector:
    app: user-manage-ldap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
