---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manage-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manage-ldap
  template:
    metadata:
      labels:
        app: user-manage-ldap
    spec:
      containers:
        - name: user-manage-ldap
          image: ${TESTING_IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: LDAP_HOST
              value: ldap
      imagePullSecrets:
        - name: regcred
