FROM osixia/phpldapadmin:stable

RUN sed -i '/nginx/d' /etc/apt/sources.list \
    && rm -f /etc/apt/sources.list.d/nginx.list \
    && sed -i 's|http://deb.debian.org|http://archive.debian.org|g' /etc/apt/sources.list \
    && sed -i 's|http://security.debian.org|http://archive.debian.org|g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=5 \
  CMD curl -f http://localhost || exit 1