---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap-server
  template:
    metadata:
      labels:
        app: openldap-server
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_ORGANISATION
              value: "SpringFramework Org"
            - name: LDAP_DOMAIN
              value: "springframework.org"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: password
          command:
            - "--copy-service"
            - "--loglevel"
            - "debug"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  ldapsearch -x -H ldap://localhost \
                    -b dc=springframework,dc=org \
                    -s base \
                    -D cn=admin,dc=springframework,dc=org \
                    -w "${LDAP_ADMIN_PASSWORD}"
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  ldapsearch -x -H ldap://localhost \
                    -b dc=springframework,dc=org \
                    -s base \
                    -D cn=admin,dc=springframework,dc=org \
                    -w "${LDAP_ADMIN_PASSWORD}"
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  selector:
    app: openldap-server
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
