---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-bootstrap-ldif
  namespace: ci
data:
  users.ldif: |
    dn: ou=groups,dc=springframework,dc=org
    objectclass: top
    objectclass: organizationalUnit
    ou: groups

    dn: uid=dbrown,ou=groups,dc=springframework,dc=org
    cn: David Brown
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Brown
    uid: dbrown
    userpassword: password5

    dn: uid=john,ou=groups,dc=springframework,dc=org
    cn: John
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: John
    uid: john
    userpassword: 12345

    dn: uid=msmith,ou=groups,dc=springframework,dc=org
    cn: Mary Smith
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Smith
    uid: msmith
    userpassword: password2

    dn: uid=pjones,ou=groups,dc=springframework,dc=org
    cn: Peter Jones
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Jones
    uid: pjones
    userpassword: password3

    dn: uid=swilliams,ou=groups,dc=springframework,dc=org
    cn: Susan Williams
    objectclass: top
    objectclass: person
    objectclass: organizationalPerson
    objectclass: inetOrgPerson
    sn: Williams
    uid: swilliams
    userpassword: password4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap-server
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap-server
  template:
    metadata:
      labels:
        app: openldap-server
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: dockerhub
      initContainers:
        - name: copy-bootstrap-ldif
          image: busybox:1.35
          command:
            ["sh", "-c", "cp -L /configmap-input/* /bootstrap-ldif-staging/"]
          volumeMounts:
            - name: bootstrap-ldif-configmap
              mountPath: /configmap-input
            - name: bootstrap-ldif-staging
              mountPath: /bootstrap-ldif-staging
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_ORGANISATION
              value: "SpringFramework Org"
            - name: LDAP_DOMAIN
              value: "springframework.org"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap
                  key: password
          volumeMounts:
            - name: bootstrap-ldif-staging
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
          args:
            - "--copy-service"
            - "--loglevel"
            - "debug"
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      volumes:
        - name: bootstrap-ldif-configmap
          configMap:
            name: openldap-bootstrap-ldif
        - name: bootstrap-ldif-staging
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
  namespace: ci
spec:
  selector:
    app: openldap-server
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
