---
name: "Build, Test, and Publish"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read
  pull-requests: write # Required to post comments on PRs
  security-events: write # Required to upload SARIF reports
  packages: write # Required to push images to ghcr.io

jobs:
  # JOB 1: Build the image, scan for vulnerabilities, and save the image as an
  # artifact. This job runs on all triggers.
  build_and_scan:
    name: Build and Scan
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag_generator.outputs.image_tag }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Generate unique image tag
        id: image_tag_generator
        run: echo "image_tag=ghcr.io/${{ github.repository_owner }}/user-manage-ldap:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for testing and scanning
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true # Load the image into the local Docker daemon
          tags: ${{ steps.image_tag_generator.outputs.image_tag }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy for CRITICAL CVEs
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ steps.image_tag_generator.outputs.image_tag }}
          format: sarif
          exit-code: 1
          vuln-type: os,library
          severity: CRITICAL
          output: trivy-results.sarif
          scanners: vuln
          # CRITICAL: This flag is REQUIRED to make the exit code respect the 'severity' setting.
          # Without it, the step fails on ANY vulnerability when using SARIF format due to a known
          # issue in the action (aquasecurity/trivy-action#386). Do not remove.
          limit-severities-for-sarif: true

      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Ensure results are uploaded even if the scan fails
        with:
          sarif_file: trivy-results.sarif
