---
name: "Build, Test, and Publish"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read
  pull-requests: write # Required to post comments on PRs
  security-events: write # Required to upload SARIF reports
  packages: write # Required to push images to ghcr.io

jobs:
  # JOB 1: Build the image, scan for vulnerabilities, and save the image as an
  # artifact. This job runs on all triggers.
  build_and_scan:
    name: Build and Scan
    runs-on: ubuntu-latest
    outputs:
      image_tag: ghcr.io/${{ github.repository_owner }}/user-manage-ldap:${{ github.sha }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for testing and scanning
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true # Load the image into the local Docker daemon
          tags: ${{ job.outputs.image_tag }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
