---
name: "Build, Test, and Publish"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read
  pull-requests: write # Required to post comments on PRs
  security-events: write # Required to upload SARIF reports
  packages: write # Required to push images to ghcr.io

jobs:
  # JOB 1: Build the image, scan for vulnerabilities, and save the image as an
  # artifact. This job runs on all triggers.
  build_and_scan:
    name: Build and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
